Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    
    #   # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  config.vm.network "private_network", ip: "10.249.0.101"
end
